### ISSUE TITLE
Hello Vaibhav, as you specified server and client directory , I'm didn't find such directories

### ISSUE THREAD

**Issue by khushi2000soni** [itsvaibhavmishra/TwinkChat-2.0#45]

**Comment by itsvaibhavmishra** [comment]
Hey @khushi2000soni, the folders server and client were changed into backend and frontend. Readme has been updated for further use. 
[Updated Readme](https://github.com/itsvaibhavmishra/TwinkChat-2.0/commit/cd2f9f2001d634cefc719ff46269f05e5e71c0b6) <-- reference to the updated readme commit.
